[project]
name = "day2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.2.2",
]

[tool.uv.workspace]
members = [
    "week1/day4",
    "week1/day5",
    "week2/day6",
    "week2/day7.py",
    "week2/day8",
]
